### ISSUE TITLE
An error on Android studio

### ISSUE THREAD

**Issue by dengxiang** [hajdam/deltahex-intellij-plugin#1]
org.exbin.deltahex.intellij.DeltaHexFileEditor.getState(Lcom/intellij/openapi/fileEditor/FileEditorStateLevel;)Lcom/intellij/openapi/fileEditor/FileEditorState;
java.lang.AbstractMethodError: org.exbin.deltahex.intellij.DeltaHexFileEditor.getState(Lcom/intellij/openapi/fileEditor/FileEditorStateLevel;)Lcom/intellij/openapi/fileEditor/FileEditorState;
	at com.intellij.openapi.command.impl.UndoManagerImpl.getCurrentState(UndoManagerImpl.java:330)
	at com.intellij.openapi.command.impl.UndoManagerImpl.commandStarted(UndoManagerImpl.java:279)
	at com.intellij.openapi.command.impl.UndoManagerImpl.onCommandStarted(UndoManagerImpl.java:236)
	at com.intellij.openapi.command.impl.UndoManagerImpl.access$100(UndoManagerImpl.java:60)
	at com.intellij.openapi.command.impl.UndoManagerImpl$2.commandStarted(UndoManagerImpl.java:182)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.fireCommandStarted(CoreCommandProcessor.java:333)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:123)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile(FileEditorManagerImpl.java:629)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile(FileEditorManagerImpl.java:642)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer$CloseTab.actionPerformed(EditorTabbedContainer.java:453)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by hajdam** [comment]
I tried to fix this. You can try snapshot with the fix here: http://deltahex.exbin.org/download.php?deltahex-intellij-plugin.jar
I'll release it later after I'll do some additional manual testing.

**Comment by hajdam** [comment]
Released version 0.1.2.

**Comment by hajdam** [comment]
As no additional issue was reported, I assume this is fixed.
